version: '3'
services:

  app:
    container_name: file-upload
    build: .
    ports: 
      - 8000:8000
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - mongo
    networks:
      - mynet

  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    env_file:
      - ./docker.env
    ports:
      - "6000:27017"
    volumes:
      - mongodb:/data/db
    networks:
      - mynet

volumes:
  mongodb:


networks:
  mynet:
    driver: bridge